### ISSUE TITLE
How to inference the bounding boxes?

### ISSUE THREAD

**Issue by jsomeara** [jinhseo/OD-WSCL#6]
Please ignore my ignorance on this topic.

I have everything installed correctly but I'm unsure how I'm supposed to actually use the model. Are the trained model weights not provided?

Does this command predict the bounding boxes?
`python -m torch.distributed.launch --nproc_per_node=1 tools/test_net.py --config-file "configs/voc/voc07_contra_db_b8_lr0.01_mcg.yaml" TEST.IMS_PER_BATCH 8 OUTPUT_DIR OD-WSCL/output MODEL.WEIGHT OD-WSCL/output/model_final.pth`

If so, I get this error:  No such file or directory: 'OD-WSCL/output/model_final.pth' which is obviously present because I do not have the model weights.

How do I get the model weights and how do I use them to predict bounding boxes for any image?

**Comment by jinhseo** [comment]
Hi, Sorry for late reply.
The error with model_final.pth occurred because you were trying to perform testing without running training code.
As for the model weights, I need to check my repository, but you may get approximate performance simply run the training code.
Regarding the last question, WSOD uses pre-defined bbox candidates. If u want to apply the model to custom dataset, you need to use SS/MCG algorithm to extract candidates for your target dataset and then run it.
