### ISSUE TITLE
Not being able to reproduce the paper result in other GPUs.

### ISSUE THREAD

**Issue by luiszeni** [jinhseo/OD-WSCL#7]
Hello, thanks for sharing the code of this great work.

I am trying, with no success, to reproduce the results reported in the paper using another GPU. I trained the model using the same environment described in the README file. I am using an Nvidia V100 with 32GB VRAM.

I used the following configurations/command to train:

python -m torch.distributed.launch --nproc_per_node=1 tools/train_net.py --config-file "configs/voc07_contra_db_b8_lr0.01_mcg.yaml" OUTPUT_DIR OD-WSCL/output nms 0.1 lmda 0.03 iou 0.5 temp 0.2

The paper reports an mAP of 58.7 for these parameters. However, after multiple trainings, my best result was 57.1 mAP. I also trained using a 3090, removing the 1200px resolution (due to memory constraints); the mAP was 57.0.

Do you know why there is this difference of 1.1 mAP? Did you train the model on other GPUs?

Also, can you please share the config.yml and weights saved in the OUTPUT_DIR of our best model?

Thank you.

**Comment by jinhseo** [comment]
Hi, the exact GPU specs used for training and evaluation is A100.
To ensure sufficient batch size, the training was conducted single GPU, which resulted in optimal performance.
While your setup may not be identical, I would recommend using multiple 3090s instead of reducing the resolution if possible.
The config.yml has already been shared, and I am currently evaluating the performance of the updated code and will also upload the weights of previous model.
